"""empty message

Revision ID: 74bd5c16013c
Revises: b783e5e26a38
Create Date: 2016-05-02 01:44:02.501579

"""

# revision identifiers, used by Alembic.
revision = '74bd5c16013c'
down_revision = 'b783e5e26a38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('praticar_questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_questao', sa.Integer(), nullable=True),
    sa.Column('alternativa_usuario', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alternativa_usuario'], ['questoes_alternativas.id'], ),
    sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('practice')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('id_questao', sa.INTEGER(), nullable=True),
    sa.Column('alternativa_usuario', sa.INTEGER(), nullable=True),
    sa.Column('data_hora', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['alternativa_usuario'], [u'questoes_alternativas.id'], ),
    sa.ForeignKeyConstraint(['id_questao'], [u'questoes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], [u'usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('praticar_questoes')
    ### end Alembic commands ###
