"""empty message

Revision ID: 91af2915d73c
Revises: None
Create Date: 2016-05-01 21:07:24.198122

"""

# revision identifiers, used by Alembic.
revision = '91af2915d73c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_conhecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('instituicoes_ensino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=25), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('privado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('sigla'),
    sa.UniqueConstraint('site')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_instituicao_ensino', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_instituicao_ensino'], ['instituicoes_ensino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instituicoes_ensino_curso',
    sa.Column('id_instituicao_ensino', sa.Integer(), nullable=True),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['id_instituicao_ensino'], ['instituicoes_ensino.id'], )
    )
    op.create_table('areas_conhecimento_pesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_concurso', sa.Integer(), nullable=True),
    sa.Column('id_area_conhecimento', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_area_conhecimento'], ['areas_conhecimento.id'], ),
    sa.ForeignKeyConstraint(['id_concurso'], ['concursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('areas_conhecimento_pesos')
    op.drop_table('instituicoes_ensino_curso')
    op.drop_table('concursos')
    op.drop_table('questoes')
    op.drop_table('instituicoes_ensino')
    op.drop_table('cursos')
    op.drop_table('areas_conhecimento')
    ### end Alembic commands ###
