"""empty message

Revision ID: b783e5e26a38
Revises: None
Create Date: 2016-05-02 01:08:25.549183

"""

# revision identifiers, used by Alembic.
revision = 'b783e5e26a38'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas_conhecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('instituicoes_ensino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=25), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('privado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('sigla'),
    sa.UniqueConstraint('site')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('concursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_instituicao_ensino', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_instituicao_ensino'], ['instituicoes_ensino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instituicoes_ensino_curso',
    sa.Column('id_instituicao_ensino', sa.Integer(), nullable=True),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['id_instituicao_ensino'], ['instituicoes_ensino.id'], ),
    sa.PrimaryKeyConstraint('id_instituicao_ensino', 'id_curso')
    )
    op.create_table('praticar_simulados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_cursos_interesse',
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_instituicao_ensino', sa.Integer(), nullable=True),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['id_instituicao_ensino'], ['instituicoes_ensino.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], )
    )
    op.create_table('usuarios_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_area_conhecimento', sa.Integer(), nullable=True),
    sa.Column('numero_acertos', sa.Integer(), nullable=True),
    sa.Column('numero_erros', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_area_conhecimento'], ['areas_conhecimento.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas_conhecimento_pesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_concurso', sa.Integer(), nullable=True),
    sa.Column('id_area_conhecimento', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_area_conhecimento'], ['areas_conhecimento.id'], ),
    sa.ForeignKeyConstraint(['id_concurso'], ['concursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_concurso', sa.Integer(), nullable=True),
    sa.Column('id_area_conhecimento', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), server_default='', nullable=False),
    sa.Column('numero_acertos', sa.Integer(), nullable=True),
    sa.Column('numero_erros', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_area_conhecimento'], ['areas_conhecimento.id'], ),
    sa.ForeignKeyConstraint(['id_concurso'], ['concursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes_alternativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_questao', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('alternativa_correta', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_questao', sa.Integer(), nullable=True),
    sa.Column('alternativa_usuario', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alternativa_usuario'], ['questoes_alternativas.id'], ),
    sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('praticar_simulados_questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_simulado', sa.Integer(), nullable=True),
    sa.Column('id_questao', sa.Integer(), nullable=True),
    sa.Column('alternativa_usuario', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alternativa_usuario'], ['questoes_alternativas.id'], ),
    sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['id_simulado'], ['praticar_simulados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes_imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_questao', sa.Integer(), nullable=True),
    sa.Column('id_questao_alternativas', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['id_questao_alternativas'], ['questoes_alternativas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questoes_imagens')
    op.drop_table('praticar_simulados_questoes')
    op.drop_table('practice')
    op.drop_table('questoes_alternativas')
    op.drop_table('questoes')
    op.drop_table('areas_conhecimento_pesos')
    op.drop_table('usuarios_relatorio')
    op.drop_table('usuarios_cursos_interesse')
    op.drop_table('praticar_simulados')
    op.drop_table('instituicoes_ensino_curso')
    op.drop_table('concursos')
    op.drop_table('usuarios')
    op.drop_table('instituicoes_ensino')
    op.drop_table('cursos')
    op.drop_table('areas_conhecimento')
    ### end Alembic commands ###
