"""empty message

Revision ID: da3ec3fba853
Revises: 91af2915d73c
Create Date: 2016-05-01 21:28:27.624183

"""

# revision identifiers, used by Alembic.
revision = 'da3ec3fba853'
down_revision = '91af2915d73c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    ### end Alembic commands ###
